

#nullable disable

using Microsoft.EntityFrameworkCore.Migrations;

namespace Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddReviewsTable : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Criar tabela Reviews apenas se não existir
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""Reviews"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""UserId"" integer NOT NULL,
                    ""OrderId"" integer NOT NULL,
                    ""Rating"" integer NOT NULL,
                    ""Comment"" character varying(500) NOT NULL,
                    ""IsApproved"" boolean NOT NULL DEFAULT false,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""UpdatedAt"" timestamp with time zone,
                    ""IsDeleted"" boolean NOT NULL,
                    CONSTRAINT ""PK_Reviews"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_Reviews_Orders_OrderId"" FOREIGN KEY (""OrderId"") REFERENCES ""Orders"" (""Id"") ON DELETE RESTRICT,
                    CONSTRAINT ""FK_Reviews_Users_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""Users"" (""Id"") ON DELETE RESTRICT
                );
            ");

            // Criar índices apenas se não existirem
            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS ""IX_Reviews_OrderId"" ON ""Reviews"" (""OrderId"");
            ");

            migrationBuilder.Sql(@"
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_Reviews_UserId"" ON ""Reviews"" (""UserId"");
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Reviews");
        }
    }
}

